# Generated by Django 5.1.2 on 2024-11-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressure',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
